project:
  type: book
  output-dir: _site

book:
  title: "Bayesianische Intuition"
  subtitle: "Ein interaktiver Workshop zur Inferenzstatistik"
  chapters:
    - chap7.qmd

execute:
  enabled: false

format:
  html:
    theme: cosmo
    toc: true
    filters:
      - shinylive
  pdf:
    documentclass: scrreprt
    lang: de
    papersize: a4
