project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - chap1.qmd
    - chap2.qmd
    - chap3.qmd
    - chap4.qmd
    - chap5.qmd
    - chap6.qmd

website:
  title: "Bayesianische Intuition"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - chap1.qmd
      - chap2.qmd
      - chap3.qmd
      - chap4.qmd
      - chap5.qmd
      - chap6.qmd

execute:
  enabled: false

format:
  html:
    theme: cosmo
    toc: true
    filters:
      - shinylive
